world-federation-of-advertisers/virtual-people-common

src/main/proto/wfa/virtual_people/common/model.proto
ConditionalMerge and UpdateTree do not require random_seed.
=> Move random_seed to UpdateMatrix and SparseUpdateMatrix.

src/main/proto/wfa/virtual_people/common/BUILD.bazel, src/main/proto/wfa/virtual_people/common/demographic.proto, src/main/proto/wfa/virtual_people/common/event.proto, src/main/proto/wfa/virtual_people/common/geo_location.proto, src/main/proto/wfa/virtual_people/common/label.proto, src/main/proto/wfa/virtual_people/common/model.proto, src/main/proto/wfa/virtual_people/common/panel_data.proto
Add VID event proto and label proto.
=> Add VID event proto and label proto.

src/main/proto/wfa/virtual_people/common/event.proto
These fingerprints are only used by VID Labeler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/10)
=> Add fingerprint fields for user id and event id.

src/main/cc/wfa/virtual_people/common/field_filter/BUILD.bazel, src/main/cc/wfa/virtual_people/common/field_filter/field_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/gt_filter.h, src/main/cc/wfa/virtual_people/common/field_filter/gt_filter_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/lt_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/lt_filter.h, src/main/cc/wfa/virtual_people/common/field_filter/lt_filter_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/BUILD.bazel, src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/13)
=> Implement FieldFilterProto with op as GT and LT.

src/main/cc/wfa/virtual_people/common/field_filter/utils/BUILD.bazel, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/15)
=> Create a library to set field in protobuf messages using reflection.

src/main/cc/wfa/virtual_people/common/field_filter/equal_filter.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/17)
=> Add virtual destructors for abstract classes.

.bazelrc, src/main/cc/wfa/virtual_people/common/field_filter/BUILD.bazel, src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter.h, src/main/cc/wfa/virtual_people/common/field_filter/any_in_filter_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/equal_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/field_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/in_filter.cc, src/main/cc/wfa/virtual_people/common/field_filter/in_filter.h, src/main/cc/wfa/virtual_people/common/field_filter/in_filter_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/test/test.proto, src/main/cc/wfa/virtual_people/common/field_filter/utils/BUILD.bazel, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/integer_comparator.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/template_util.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util_test.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.cc, src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser.h, src/main/cc/wfa/virtual_people/common/field_filter/utils/values_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/16)
=> Implement IN and ANY_IN field filter

.github/workflows/build-test.yml, .github/workflows/lint.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/19)
=> Add GitHub actions to lint and run Bazel tests

src/main/proto/wfa/virtual_people/common/demographic.proto, src/main/proto/wfa/virtual_people/common/model.proto
Add multiplicity related fields to LabelerEvent.
Remove open_age_bucket field from AgeRange. For open age bucket, set max_age to 1000.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/22)
=> Update a few proto.

src/test/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, src/test/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/28)
=> Check for Status explicitly when calling IsOk.

src/test/cc/wfa/virtual_people/common/field_filter/BUILD.bazel, src/test/cc/wfa/virtual_people/common/field_filter/true_filter_test.cc, src/test/cc/wfa/virtual_people/common/field_filter/utils/field_util_test.cc, src/test/cc/wfa/virtual_people/common/field_filter/utils/type_convert_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/29)
Remove unused "using" statement.
Fix tests for TRUE filter.
=> Minor fixes.

WORKSPACE, src/main/proto/wfa/virtual_people/common/demographic.proto, src/main/proto/wfa/virtual_people/common/event.proto, src/main/proto/wfa/virtual_people/common/field_filter.proto, src/main/proto/wfa/virtual_people/common/geo_location.proto, src/main/proto/wfa/virtual_people/common/label.proto, src/main/proto/wfa/virtual_people/common/model.proto, src/main/proto/wfa/virtual_people/common/panel_data.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/33)
=> add java packages to all protos

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtil.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtilTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/40)
=> Implement type convert util functions.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/ValuesParser.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/ValuesParserTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/41)
=> Implement value parsers.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/42)
=> Implement the kotlin HasFilter.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtilTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/44)
=> Implement the kotlin AnyInFilter.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AndFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AndFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilterTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/45)
=> Implement the kotlin AndFilter and OrFilter.

src/main/proto/wfa/virtual_people/common/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/47)
=> Add kt_jvm_proto targets for common protos

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtil.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/46)
=> Message filter util implementation

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AndFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/EqualFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtil.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/ValuesParser.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilterTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/48)
=> Update AnyInFilter to use generic subclasses.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/49)
=> Integer Comparator util

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/PartialFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/PartialFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/50)
=> Implement the Kotlin PartialFilter class.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/51)
=> Gt Filter and Lt Filter

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/FieldFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/InFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/NotFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/TrueFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/BUILD.bazel, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/InFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/NotFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/TrueFilterTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/52)
=> Not, true and in filter implementation

src/main/proto/wfa/virtual_people/common/event.proto, src/main/proto/wfa/virtual_people/common/model.proto
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/53)
=> Add notes to all fingerprint fields in our protos.

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AndFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/PartialFilter.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AndFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/EqualFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/HasFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/OrFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/PartialFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/MessageFilterUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/ValuesParserTest.kt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/57)
=> Add message error validation for exceptions in tests

src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/AnyInFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/EqualFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/GtFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/InFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/LtFilter.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtil.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtil.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtil.kt, src/main/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/ValuesParser.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/InFilterTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/FieldUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/IntegerComparatorUtilTest.kt, src/test/kotlin/org/wfanet/virtualpeople/common/fieldfilter/utils/TypeConvertUtilTest.kt
The proto field is read as Int and Long, we need to manually convert them to UInt and ULong before comparison.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/54)
=> Read/write/compare uint32 and uint64 proto fields as unsigned values.
